-- Insert all 25 prompt types
INSERT INTO `ctoteam.prism.prism_prompt_types`
  (prompt_type_id, name, category, template, input_vars, description, where_to_apply, example, use_case, created_at)
VALUES
  ('PT001', 'Instruction-Based',                    'Instruction', 'Perform the following task: {task}',                                      JSON '["task"]',          'Direct instructions to perform a specific task.',                                      'Direct task execution',           'Summarize an article.',                                  'Content summarization',             CURRENT_TIMESTAMP()),
  ('PT002', 'Chain-of-Thought',                     'Reasoning',   'Solve the problem step-by-step: {problem}',                               JSON '["problem"]',       'Step-by-step reasoning process for complex tasks.',                                   'Complex problem-solving',         'Solve a math problem step-by-step.',                     'Math problem solving',              CURRENT_TIMESTAMP()),
  ('PT003', 'Zero-Shot',                            'Instruction', 'Answer the following question: {question}',                               JSON '["question"]',      'Generates an answer without prior examples.',                                         'General knowledge queries',       'Answer a trivia question.',                              'Trivia and general knowledge',      CURRENT_TIMESTAMP()),
  ('PT004', 'Few-Shot',                             'Few-Shot',    'Given examples, classify the following input: {input}',                   JSON '["input"]',         'Uses a few examples to guide the response.',                                          'Example-driven tasks',            'Classify text with examples.',                           'Data classification',               CURRENT_TIMESTAMP()),
  ('PT005', 'Self-Consistency',                     'Reasoning',   'Provide multiple reasoning paths and the best answer: {question}',        JSON '["question"]',      'Generates multiple reasoning paths and selects the most consistent answer.',           'Tasks requiring high consistency', 'Solve arithmetic with multiple approaches.',              'Complex arithmetic reasoning',      CURRENT_TIMESTAMP()),
  ('PT006', 'Tree-of-Thoughts',                     'Reasoning',   'Explore options using tree-like reasoning for: {puzzle}',                 JSON '["puzzle"]',        'Organizes thoughts into a tree structure for exploring multiple paths.',               'Exploratory problem-solving',     'Choose the best path for solving a logic puzzle.',       'Strategic game playing',            CURRENT_TIMESTAMP()),
  ('PT007', 'Graph-of-Thought',                     'Reasoning',   'Connect concepts related to: {topic}',                                   JSON '["topic"]',         'Models non-linear, interconnected thought processes.',                                'Non-linear reasoning tasks',      'Draw connections between concepts.',                     'Creative writing and ideation',     CURRENT_TIMESTAMP()),
  ('PT008', 'Skeleton-of-Thought',                  'Reasoning',   'Outline your reasoning steps to solve: {task}',                          JSON '["task"]',          'Uses a skeleton framework to outline reasoning steps.',                               'Structured reasoning tasks',      'Outline a plan for solving a complex task.',             'Project planning and execution',    CURRENT_TIMESTAMP()),
  ('PT009', 'Chain-of-Verification',                'Reasoning',   'Verify each step logically for: {argument}',                             JSON '["argument"]',      'Verifies each step of reasoning before proceeding.',                                  'Verification-driven tasks',       'Verify the steps in a logical argument.',                'Academic research and analysis',    CURRENT_TIMESTAMP()),
  ('PT010', 'ReAct',                                'Agentic',     'React to the input and decide next action: {situation}',                  JSON '["situation"]',     'Uses reaction-based prompts for dynamic response generation.',                        'Dynamic and interactive tasks',   'Respond to changes in a conversation.',                  'Adaptive chatbots',                 CURRENT_TIMESTAMP()),
  ('PT011', 'Active-Prompt',                        'Instruction', 'Ask the user for clarification on: {task}',                              JSON '["task"]',          'Generates prompts that actively involve the user.',                                   'User-guided tasks',               'Interact with a user for task clarification.',           'Interactive tutorials',             CURRENT_TIMESTAMP()),
  ('PT012', 'Instruction Prompting and Tuning',     'Instruction', 'Tune the following response using instructions: {response}',             JSON '["response"]',      'Fine-tunes responses through instructional prompting.',                               'Fine-tuning LLM responses',       'Tune a response to a specific instruction set.',         'Customized AI applications',        CURRENT_TIMESTAMP()),
  ('PT013', 'Recursive Prompting',                  'Reasoning',   'Build a sequence of prompts to solve: {complex_task}',                   JSON '["complex_task"]',  'Generates a sequence of prompts for complex tasks.',                                  'Multi-step reasoning tasks',      'Build upon previous prompts for complex solutions.',     'Automated problem solving',         CURRENT_TIMESTAMP()),
  ('PT014', 'Automatic Prompt Engineer (APE)',       'Instruction', 'Suggest the best prompting strategy for: {goal}',                       JSON '["goal"]',          'Automatically generates optimal prompts.',                                            'Optimizing prompt strategies',    'Find the best prompt for arithmetic.',                   'Prompt optimization',               CURRENT_TIMESTAMP()),
  ('PT015', 'Automatic Reasoning and Tool-use (ART)','Agentic',   'Use tools to solve this: {tool_task}',                                   JSON '["tool_task"]',     'Integrates tool use within reasoning steps.',                                         'Tasks requiring external tools',  'Solve a task using a calculator tool.',                  'Tool integration in tasks',         CURRENT_TIMESTAMP()),
  ('PT016', 'Retrieval Augmented Generation (RAG)', 'Retrieval',   'Retrieve facts and answer this: {question}',                             JSON '["question"]',      'Augments responses with external knowledge retrieval.',                               'Knowledge-intensive tasks',       'Answer a question using Wikipedia.',                     'Up-to-date factual responses',      CURRENT_TIMESTAMP()),
  ('PT017', 'Chain-of-Note',                        'Retrieval',   'Create notes from: {document}',                                          JSON '["document"]',      'Generates reading notes for better document understanding.',                          'Improving document comprehension','Summarize key points from documents.',                   'Document analysis and synthesis',   CURRENT_TIMESTAMP()),
  ('PT018', 'Chain-of-Knowledge',                   'Retrieval',   'Incorporate knowledge and answer: {factual_query}',                      JSON '["factual_query"]', 'Dynamically incorporates external knowledge for grounding.',                          'Grounding LLMs in factual knowledge','Answer a question with up-to-date information.',       'Dynamic knowledge integration',     CURRENT_TIMESTAMP()),
  ('PT019', 'Chain-of-Code',                        'Agentic',     'Write and run code to solve: {problem}',                                 JSON '["problem"]',       'Integrates code execution within reasoning.',                                         'Programming and logic tasks',     'Execute code to solve a problem.',                       'Coding and programming tasks',      CURRENT_TIMESTAMP()),
  ('PT020', 'Chain-of-Symbol',                      'Reasoning',   'Navigate the symbolic space to: {spatial_task}',                        JSON '["spatial_task"]',  'Uses symbolic representations for spatial reasoning.',                               'Spatial reasoning tasks',         'Navigate a robot through obstacles.',                    'Robotics and spatial navigation',   CURRENT_TIMESTAMP()),
  ('PT021', 'Structured Chain-of-Thought',          'Reasoning',   'Use structured steps to solve: {program_task}',                          JSON '["program_task"]',  'Employs structured reasoning for code generation.',                                  'Code generation',                 'Generate a program to calculate Fibonacci numbers.',     'Algorithm design and optimization', CURRENT_TIMESTAMP()),
  ('PT022', 'Contrastive Chain-of-Thought',         'Reasoning',   'Show valid/invalid examples to reason: {input}',                        JSON '["input"]',         'Improves reasoning with valid and invalid examples.',                                 'Enhancing LLM reasoning',         'Identify incorrect reasoning in problem-solving.',       'Critical thinking and analysis',    CURRENT_TIMESTAMP()),
  ('PT023', 'Logical Chain-of-Thought',             'Reasoning',   'Apply logical reasoning to: {logic_problem}',                            JSON '["logic_problem"]', 'Incorporates logical principles into reasoning.',                                     'Logical reasoning tasks',         'Apply logical deductions in reasoning.',                 'Legal and ethical reasoning',       CURRENT_TIMESTAMP()),
  ('PT024', 'System 2 Attention Prompting',         'Reasoning',   'Refocus and extract main points from: {text}',                           JSON '["text"]',          'Focuses on relevant information by regenerating context.',                            'Improving attention and relevance','Focus on the main points in a long text.',               'Focus and productivity enhancement',CURRENT_TIMESTAMP()),
  ('PT025', 'Emotion Prompting',                    'Emotional',   'Add emotional intelligence and respond to: {emotion_query}',             JSON '["emotion_query"]', 'Enhances LLM performance with emotional cues.',                                      'Tasks benefiting from emotional intelligence','Generate responses to emotionally charged queries.','Emotionally aware computing',       CURRENT_TIMESTAMP());